apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
  namespace: python-app-ns
spec:
  selector:
    app: python-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: NodePort # 或 NodePort，如果您想從 k3s 節點外部訪問
